export const BOOKS_SUCCESS = 'BOOKS_SUCCESS';
export const BOOKS_FAILURE = 'BOOKS_FAILURE';

export const MOVIES_SUCCESS = 'MOVIES_SUCCESS';
export const MOVIES_FAILURE = 'MOVIES_FAILURE';

export const MOVIE_SUCCESS = 'MOVIE_SUCCESS';
export const MOVIE_FAILURE = 'MOVIE_FAILURE';

export const CHARACTER_PAGE_SUCCESS = 'CHARACTER_PAGE_SUCCESS';
export const CHARACTER_PAGE_FAILURE = 'CHARACTER_PAGE_FAILURE';
export const CURRENT_CHARACTER_PAGE = 'CURRENT_CHARACTER_PAGE';
export const FILTER_IS_VISIBLE = 'FILTER_IS_VISIBLE';
export const ASCENDING = 'ASCENDING';
export const DESCENDING = 'DESCENDING';
export const SEARCH_IS_VISIBLE = 'SEARCH_IS_VISIBLE';
export const SEARCH_VALUE = 'SEARCH_VALUE';

export const CHARACTER_SUCCESS = 'CHARACTER_SUCCESS';
export const CHARACTER_FAILURE = 'CHARACTER_FAILURE';

export const QUOTE_PAGE_SUCCESS = 'QUOTE_PAGE_SUCCESS';
export const QUOTE_PAGE_FAILURE = 'QUOTE_PAGE_FAILURE';
export const CURRENT_QUOTE_PAGE = 'CURRENT_QUOTE_PAGE';

export const CHAPTERS_SUCCESS = 'CHAPTERS_SUCCESS';
export const CHAPTERS_FAILURE = 'CHAPTERS_FAILURE';